import pyperclip
from comandos import *
from linksDeNavegacion import *
from resolucionPantalla import *




"""
def enviosPrinc(numRemision):
    
    print(numRemision)
    
    nuevapestaña()
    escribirMensaje(baseGuias)
    esperarSegundos(1)
    teclaEnter()
    esperarSegundos(5)
    buscarEnSheets()
    esperarSegundos(1)
    escribirMensaje(numRemision)
    teclaEnter()
    esperarSegundos(1)
    teclaEsc()
    esperarSegundos(5)
    variasVecesTeclas(teclaDerecha,2,1)
    controlC()
    numeroCel=pyperclip.paste()
    print(numeroCel)
    nuevapestaña()
    escribirMensaje(linkwhatsapp)
    teclaEnter()

    for i in range (7):
        print(i)
        esperarSegundos(1)
    nuevoChat()
    esperarSegundos(3)
    escribirMensaje(numeroCel)
    esperarSegundos(4)
    
    posiciones = cargar_posiciones()
    print(posiciones)
    #Nuevo Chat
    xmouse4, ymouse4 = posiciones["4"]["x"], posiciones["4"]["y"]
    #Escribir Cha
    xmouse5, ymouse5 = posiciones["5"]["x"], posiciones["5"]["y"]    
    
    enviarMouse(xmouse4,ymouse4)
    clickIzquierdo()
    enviarMouse(xmouse5,ymouse5)
    clickIzquierdo()
    irNumeroVentana(2)
    esperarSegundos(2)
    variasVecesTeclas(teclaDerecha,3,1)
    esperarSegundos(1)
    controlC()
    irNumeroVentana(3)
    enviarMouse(xmouse5,ymouse5)
    clickIzquierdo()
    controlv()    
    esperarSegundos(1)
    teclaEnter()
    irNumeroVentana(2)
    variasVecesTeclas(volverAtras,2,0.7)
    abrirvinculo()
    esperarSegundos(3)
    controlC()
    cerrarpestaña()
    esperarSegundos(2)
    irNumeroVentana(3)
    esperarSegundos(5)
    enviarMouse(xmouse5,ymouse5)
    clickIzquierdo()
    controlv()
    esperarSegundos(2)
    teclaEnter()
    esperarSegundos(5)
    archivarchat()
    esperarSegundos(5)
    cerrarpestaña()
    esperarSegundos(5)
    marcarComoHecho(numRemision)
def marcarComoHecho(numRemision):
    irNumeroVentana(2)
    variasVecesTeclas(volverAtras,8,0.7)
    controlC()
    movmiento=pegarEnVariable()
    if movmiento == numRemision:
        print("Verificacion Hecha OK")
        variasVecesTeclas(teclaDerecha,4,0.7)
        controlC()
        marcarBase= pegarEnVariable()
        if marcarBase == "1-ALISTAMIENTO":
            abrirUrl()
            escribirMensaje(guias)
            teclaEnter()
            esperarSegundos(5)
            buscarEnSheets()
            escribirMensaje(numRemision)
            variasVecesTeclas(teclaTab,2,1)
            flechaAbajo()
            esperarSegundos(1)
            flechaAbajo()
            esperarSegundos(1)
            teclaEnter()
            variasVecesTeclas(teclaTab,7,1)
            teclaEnter()
            esperarSegundos(2)
            teclaEsc()
            esperarSegundos(1)
            variasVecesTeclas(teclaTab,7,1)
            escribirMensaje("Enviado alistado")
            esperarSegundos(1)
            teclaEnter()
            esperarSegundos(1)
            cerrarpestaña()
            irNumeroVentana(1)
            acutalizacionFinal(numRemision)
        elif marcarBase == "2-EMPACADO":
            abrirUrl()
            escribirMensaje(guias)
            teclaEnter()
            esperarSegundos(5)
            buscarEnSheets()
            escribirMensaje(numRemision)
            variasVecesTeclas(teclaTab,2,1)
            flechaAbajo()
            esperarSegundos(1)
            flechaAbajo()
            esperarSegundos(1)
            teclaEnter()
            variasVecesTeclas(teclaTab,7,1)
            teclaEnter()
            esperarSegundos(2)
            teclaEsc()
            esperarSegundos(1)
            variasVecesTeclas(teclaTab,10,1)
            escribirMensaje("Enviado empacado")
            esperarSegundos(1)
            teclaEnter()
            esperarSegundos(1)
            cerrarpestaña()
            irNumeroVentana(1)
            acutalizacionFinal(numRemision)
        elif marcarBase =="3-GUIAS":
            abrirUrl()
            escribirMensaje(guias)
            teclaEnter()
            esperarSegundos(5)
            buscarEnSheets()
            escribirMensaje(numRemision)
            variasVecesTeclas(teclaTab,2,1)
            flechaAbajo()
            esperarSegundos(1)
            flechaAbajo()
            esperarSegundos(1)
            teclaEnter()
            variasVecesTeclas(teclaTab,7,1)
            teclaEnter()
            esperarSegundos(2)
            teclaEsc()
            esperarSegundos(1)
            variasVecesTeclas(teclaTab,14,1)
            escribirMensaje("Enviado Guia")
            esperarSegundos(1)
            teclaEnter()
            esperarSegundos(1)
            esperarSegundos(2)
            cerrarpestaña()
            irNumeroVentana(1)
            acutalizacionFinal(numRemision)
def acutalizacionFinal (numRemision):
    print(numRemision," Ingreso al final")
    esperarSegundos(1)

    nuevapestaña()
    esperarSegundos(1)
    escribirMensaje(tablaDinamicaGuia)
    teclaEnter()
    for i in range (7):
        esperarSegundos(1)
        print("Segundo Actualizar ", i)
    cerrarpestaña()
    irNumeroVentana(1)
    """
def enviosPrinc(numRemision):
    nuevapestaña()
    esperarSegundos
    escribirMensaje(guias)
    teclaEnter()
    esperarSegundos(5)
    buscarEnSheets()
    escribirMensaje(numRemision)
    esperarSegundos(1)
    teclaEnter()
    esperarSegundos(1)
    teclaEsc()
    esperarSegundos(1)
    controlC()
    esperarSegundos(2)
    numeroCliente=pyperclip.paste()
    esperarSegundos(2)
    teclaDerecha()
    teclaDerecha()
    esperarSegundos(2)
    controlC()
    tipoMovimiento=pyperclip.paste()

    teclaDerecha()
    controlC()
    whatsappEnviar(numeroCliente, numRemision,tipoMovimiento)
    
def whatsappEnviar(numeroCliente, numRemision, tipoMovimiento):
    abrirwhatsapp()
    esperarSegundos(2)
    nuevoChat()
    esperarSegundos(3)
    escribirMensaje(numeroCliente)
    esperarSegundos(4)
    posiciones = cargar_posiciones()

    
    #Nuevo Chat
    xmouse4, ymouse4 = posiciones["4"]["x"], posiciones["4"]["y"]
    #Escribir Cha
    xmouse5, ymouse5 = posiciones["5"]["x"], posiciones["5"]["y"]

    enviarMouse(xmouse4,ymouse4)
    clickIzquierdo()
    enviarMouse(xmouse5,ymouse5)
    clickIzquierdo()
    controlv()
    esperarSegundos(1)
    teclaEnter()

    irNumeroVentana(2)
    esperarSegundos(1)
    teclaIzquierda()
    teclaIzquierda()
    abrirvinculo()
    esperarSegundos(2)
    irNumeroVentana(3)
    esperarSegundos(3)
    enviarMouse(xmouse4,ymouse4)
    clickDerecho()
    esperarSegundos(3)
    flechaAbajo()
    flechaAbajo()
    flechaAbajo()
    teclaEnter()
    esperarSegundos(1)
    irNumeroVentana(4)

    enviarMouse(xmouse5,ymouse5)
    clickIzquierdo()
    controlv()
    esperarSegundos(1)
    teclaEnter()
    esperarSegundos(2)

    archivarchat()

    cerrarpestaña()
    esperarSegundos(1)
    cerrarpestaña()
    esperarSegundos(1)
    cerrarpestaña()
    esperarSegundos(1)
    marcarEnviado(numRemision, tipoMovimiento)


def marcarEnviado(numRemision, tipoMovimiento):
    if tipoMovimiento== "1-ALISTAMIENTO":
        abrirUrl()
        escribirMensaje(guiasMarcarHecho)
        teclaEnter()
        esperarSegundos(5)
        buscarEnSheets()
        esperarSegundos(1)
        escribirMensaje(numRemision)
        teclaEnter()
        esperarSegundos(2)
        teclaEsc()
        esperarSegundos(1)
        variasVecesTeclas(teclaDerecha,8,0.5)
        esperarSegundos(1)
        escribirMensaje("Envio Alistado")
        teclaDerecha()
    elif tipoMovimiento== "2-EMPACADO":
        abrirUrl()
        escribirMensaje(guiasMarcarHecho)
        teclaEnter()
        esperarSegundos(5)
        buscarEnSheets()
        esperarSegundos(1)
        escribirMensaje(numRemision)
        teclaEnter()
        esperarSegundos(2)
        teclaEsc()
        esperarSegundos(1)
        variasVecesTeclas(teclaDerecha,11,0.5)
        esperarSegundos(1)
        escribirMensaje("Envio Empacado")
        teclaDerecha()
    
    elif tipoMovimiento== "3-GUIAS":
        abrirUrl()
        escribirMensaje(guiasMarcarHecho)
        teclaEnter()
        esperarSegundos(5)
        buscarEnSheets()
        esperarSegundos(1)
        escribirMensaje(numRemision)
        teclaEnter()
        esperarSegundos(2)
        teclaEsc()
        esperarSegundos(1)
        variasVecesTeclas(teclaDerecha,15,0.5)
        esperarSegundos(1)
        escribirMensaje("Enviado Guia")
        teclaDerecha()
    esperarSegundos(8)
    abrirUrl()
    escribirMensaje(tomaDeDecisiones)
    teclaEnter()
    esperarSegundos(8)
    




